import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const marker = '<!-- Generated by duckposting. Run prepareJekyll to update. -->';
const safeDirectory = value => typeof value === 'string' && value && !/^(?:\/|[A-Za-z]:)/.test(value)
  && !/[\\\u0000-\u001f]/.test(value) && !value.split('/').some(part => ['', '.', '..'].includes(part));
// Escape Liquid's opening braces inside JSON strings, preserving {{date}} and
// renderer-specific syntax until the browser decodes the configuration.
const scriptJSON = value => JSON.stringify(value).replace(/"(?:[^"\\]|\\.)*"/g,
  literal => literal.replace(/</g, '\\u003c').replace(/{/g, '\\u007b'));

/** Prepare static Jekyll files. No Ruby plugin or runtime Node server. */
export async function prepareJekyll(options, assetsDir = dirname(fileURLToPath(import.meta.url))) {
  const { source = '.', repository, branch = 'main', layout = 'default', postLayout = 'post', template } = options || {};
  if (source !== '.' && !safeDirectory(source)) throw new Error('duckposting: source must be a repository-relative directory or .');
  if (!/^[\w-]+\/[\w.-]+$/.test(repository || '')) throw new Error('duckposting: configure repository as owner/repository.');
  if (typeof branch !== 'string' || !branch.trim()) throw new Error('duckposting: configure a nonempty GitHub branch.');
  if (typeof layout !== 'string' || typeof postLayout !== 'string' || template != null && typeof template !== 'string') throw new Error('duckposting: layout names and template must be text.');
  const prefix = source === '.' ? '' : `${source}/`, root = resolve(source);
  const directory = join(root, 'duckposting'), write = join(root, 'write.html');
  const existing = await readFile(write, 'utf8').catch(error => { if (error.code !== 'ENOENT') throw error; });
  if (existing && !existing.includes(marker)) throw new Error('duckposting: write.html already exists. Move it before preparing the editor.');
  const files = await readdir(root);
  if (files.includes('write.md') || files.includes('write')) throw new Error('duckposting reserves /write/. Move write.md or the write directory first.');
  const generated = await readFile(join(directory, '.generated'), 'utf8').catch(error => { if (error.code !== 'ENOENT') throw error; });
  if (files.includes('duckposting') && generated !== 'duckposting\n') throw new Error('duckposting: duckposting directory already exists and is not generated by this tool.');
  const assets = await Promise.all(['editor.js', 'editor.css'].map(file => readFile(join(assetsDir, file))));
  const fonts = await readdir(join(assetsDir, 'fonts'));
  await readFile(join(assetsDir, 'THIRD_PARTY_LICENSES.txt'));
  const version = createHash('sha256').update(assets[0]).update(assets[1]).digest('hex').slice(0, 12);
  const settings = { repository, branch, contentRoot: `${prefix}_posts`, contentDir: `${prefix}_posts`,
    imageDir: `${prefix}assets/images`, filenameFormat: 'date-title', draftField: 'published', draftValue: false,
    publishedLinksOnly: true,
    template: template ?? `---\nlayout: ${JSON.stringify(postLayout)}\ntitle: ""\ndate: {{date}}\npublished: true\n---\n\n` };
  const page = `---
layout: ${JSON.stringify(layout)}
title: Write
permalink: /write/
sitemap: false
---
${marker}
<link rel="stylesheet" href="{{ '/duckposting/editor.css' | relative_url }}?v=${version}">
<div id="duckposting"><p>Loading duckposting…</p><noscript>Enable JavaScript to write.</noscript></div>
<script type="module">
import { mountDuckposting } from {{ '/duckposting/editor.js' | relative_url | append: '?v=${version}' | jsonify }};
const root = document.getElementById('duckposting');
try {
  {% if site.unpublished or site.show_drafts %}
  throw new Error('Disable unpublished and show_drafts in public Jekyll builds before using duckposting.');
  {% endif %}
  await mountDuckposting(root, {
    ...${scriptJSON(settings)},
    siteBase: {{ '/' | relative_url | jsonify }},
    imageBase: {{ '/assets/images/' | relative_url | jsonify }},
    index: {{ '/duckposting/content.json' | relative_url | jsonify }}
  });
} catch (error) { root.textContent = 'Could not load duckposting. ' + error.message; }
</script>
`;
  // Jekyll supplies final URLs, including categories, custom permalinks and baseurl.
  // Only published _posts metadata reaches the public index, never draft titles.
  const index = `---
layout: null
permalink: /duckposting/content.json
---
[{% assign separator = '' %}{% for post in site.posts %}{% assign folder = post.path | slice: 0, 7 %}{% assign extension = post.path | split: '.' | last | downcase %}{% if folder == '_posts/' and extension == 'md' and post.published != false %}{{ separator }}{"path":{{ post.path | prepend: ${JSON.stringify(prefix)} | jsonify }},"title":{{ post.title | append: '' | jsonify }},"url":{{ post.url | relative_url | jsonify }}}{% assign separator = ',' %}{% endif %}{% endfor %}]
`;
  await mkdir(join(directory, 'fonts'), { recursive: true });
  for (const file of ['editor.js', 'editor.css', 'THIRD_PARTY_LICENSES.txt']) await copyFile(join(assetsDir, file), join(directory, file));
  for (const file of fonts) await copyFile(join(assetsDir, 'fonts', file), join(directory, 'fonts', file));
  await writeFile(join(directory, 'content.json'), index);
  await writeFile(write, page);
  await writeFile(join(directory, '.generated'), 'duckposting\n');
  return { write, directory };
}
