import { fileURLToPath } from "node:url";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
const project = dirname(fileURLToPath(import.meta.url));
const target = process.argv[2];
if (!target) throw new Error("Usage: node copy-to-blog.mjs /path/to/blog");
const directory = resolve(target, "duckposting");
await mkdir(directory, { recursive: true });
for (const file of ["editor.js", "editor.css", "THIRD_PARTY_LICENSES.txt"]) await copyFile(resolve(project, `dist/${file}`), resolve(directory, file));
await copyFile(resolve(project, "packages/quartz/index.tsx"), resolve(directory, "index.tsx"));
await copyFile(resolve(project, "LICENSE"), resolve(directory, "LICENSE"));
await copyFile(resolve(project, "CHANGELOG.md"), resolve(directory, "CHANGELOG.md"));
await copyFile(resolve(project, "packages/quartz/README.md"), resolve(directory, "README.md"));
const { version } = JSON.parse(await readFile(resolve(project, "package.json"), "utf8"));
await writeFile(resolve(directory, "VERSION"), `${version}\n`);
console.log(`Copied duckposting to ${directory}`);
