import { mkdir, copyFile, readFile, writeFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const project = dirname(fileURLToPath(import.meta.url));
await import('./build.mjs');
const { version } = JSON.parse(await readFile(join(project, 'package.json'), 'utf8'));
const stage = join(project, 'dist', `duckposting-${version}`), folder = join(stage, 'duckposting');
await rm(stage, { recursive: true, force: true });
await mkdir(folder, { recursive: true });
for (const file of ['editor.js', 'editor.css', 'THIRD_PARTY_LICENSES.txt']) await copyFile(join(project, 'dist', file), join(folder, file));
for (const [source, target] of [['packages/quartz/index.tsx', 'index.tsx'], ['packages/quartz/README.md', 'README.md'], ['LICENSE', 'LICENSE']]) await copyFile(join(project, source), join(folder, target));
await writeFile(join(folder, 'VERSION'), `${version}\n`);
const archive = join(project, 'dist', `duckposting-${version}.zip`);
await rm(archive, { force: true });
await promisify(execFile)('zip', ['-q', '-r', archive, 'duckposting'], { cwd: stage });
console.log(`Release candidate: ${archive}`);
